# Spring Boot Application Configuration
# This configuration demonstrates:
# - YAML configuration format (compare with JSON in C#)
# - Environment-specific configurations
# - Logging configuration
# - Server configuration

spring:
  application:
    name: ticket-booking-system
  
  # Profile configuration
  profiles:
    active: dev
  
  # Jackson Configuration for JSON serialization
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  
  # DevTools Configuration (development only)
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

# Logging Configuration
logging:
  level:
    root: INFO
    com.coherentsolutions.ticketbookingsystem: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management and Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# Application-specific Configuration
app:
  name: "Ticket Booking System"
  version: "1.0.0"
  description: "REST API for ticket booking system"
  
  # API Configuration
  api:
    version: "v1"
    base-path: "/api/v1"
    
  # Pagination Configuration
  pagination:
    default-page-size: 10
    max-page-size: 100

# TODO: Students should add database configuration when implementing persistence
# TODO: Add security configuration when implementing authentication
# TODO: Add external service configurations as needed